apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: fqzqd4dq3-java-springboot-gitops-repository
spec:
  url: https://github.com/rhopp-rhtap-testing/fqzqd4dq3-java-springboot-gitops